<?xml version="1.0" encoding="utf-8"?><Database Name="PlegitDB" EntityNamespace="UserMgt.Entity" ContextNamespace="UserMgt.DAL" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MuQaddas\MSSQLSERVER01;Initial Catalog=PlegitDB;Persist Security Info=True;User ID=sada;Pooling=True;Min Pool Size=0;Max Pool Size=100;Connect Timeout=60;Trust Server Certificate=True" SettingsObjectName="DeffinityManager.Properties.Settings" SettingsPropertyName="PlegitDBConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QuickLinks" Member="QuickLinks">
    <Type Name="QuickLink">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuickLinksDefault" Member="QuickLinksDefaults">
    <Type Name="QuickLinksDefault">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="PositionInList" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortalDashBoardOpt" Member="PortalDashBoardOpts">
    <Type Name="PortalDashBoardOpt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportName" Type="System.String" DbType="VarChar(450)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.portaldashboardrpts" Member="portaldashboardrpts">
    <Type Name="portaldashboardrpt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RportName" Type="System.String" DbType="VarChar(450)" CanBeNull="true" />
      <Column Name="ReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InboxMessages" Member="InboxMessages">
    <Type Name="InboxMessage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Gid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceivedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsViewed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FromAddress" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ToAddress" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractorDetails" Member="ContractorDetails">
    <Type Name="ContractorDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowFinancialCosts" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultCustomerSite" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserPasswordReset" Member="UserPasswordResets">
    <Type Name="UserPasswordReset">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RandomID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForgotPasswordInfo" Member="ForgotPasswordInfos">
    <Type Name="ForgotPasswordInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verifyCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Currenttime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserSkills" Member="UserSkills">
    <Type Name="UserSkill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Skills" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateBooked" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PasswordExpiryConfig" Member="PasswordExpiryConfigs">
    <Type Name="PasswordExpiryConfig">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Expirytype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResourceSchedule" Member="ResourceSchedules">
    <Type Name="ResourceSchedule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ResourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Contractor_ResourceSchedule" Member="Contractor" ThisKey="ResourceID" OtherKey="ID" Type="Contractor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAssociatedPostcodes" Member="UserAssociatedPostcodes">
    <Type Name="UserAssociatedPostcode">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Contractor_UserAssociatedPostcode" Member="Contractor" ThisKey="UserID" OtherKey="ID" Type="Contractor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.messagedataV" Member="messagedataVs">
    <Type Name="messagedataV">
      <Column Name="msgid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fromid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="toid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAssociateToType" Member="UserAssociateToTypes">
    <Type Name="UserAssociateToType">
      <Column Name="UATID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MakeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Contractor_UserAssociateToType" Member="Contractor" ThisKey="UserID" OtherKey="ID" Type="Contractor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserToCompany" Member="UserToCompanies">
    <Type Name="UserToCompany">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyUsers" Member="CompanyUsers">
    <Type Name="CompanyUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaxReference" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Payment_vendor" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Payment_username" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Payment_password" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Payment_host" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UpgradDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrainingDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDetails" Member="UserDetails">
    <Type Name="UserDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Disable_CustomerPortalAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccesstoProjectFinancials" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsercandeleteitemsfromtheInventory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExpertiseTypeID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RangeCovered" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DenominationDetailsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubDenominationDetailsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmailAddress2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GroupDetailsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Chat_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Chat_Key" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_contractors" Member="v_contractors">
    <Type Name="v_contractor">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractorName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupOwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeApproveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NormalBuyingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NormalSellingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeBuyingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeSellingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EmploymentStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpClassification" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondTSApprover" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isFirstlogin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CasualLabourType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractorType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PrimaryTimesheetApproverName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SecondaryTimesheetApproverName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PartnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartnerName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DenominationDetailsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupDetailsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubDenominationDetailsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DenominationDetailsName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DenominationGroupDetailsName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SubDenominationDetailsName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TypeofLogin" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Chat_ID" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Chat_Key" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SkillTags" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Contractors" Member="Contractors">
    <Type Name="Contractor">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractorName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupOwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeApproveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NormalBuyingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NormalSellingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeBuyingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeSellingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EmploymentStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpClassification" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondTSApprover" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isFirstlogin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CasualLabourType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ForcePeriodicPwd" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResetPassword" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CalendarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeofLogin" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImageData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="pkey" Type="System.String" DbType="NVarChar(320)" CanBeNull="true" />
      <Column Name="WantsTutorial" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Contractor_ResourceSchedule" Member="ResourceSchedules" ThisKey="ID" OtherKey="ResourceID" Type="ResourceSchedule" />
      <Association Name="Contractor_UserAssociatedPostcode" Member="UserAssociatedPostcodes" ThisKey="ID" OtherKey="UserID" Type="UserAssociatedPostcode" />
      <Association Name="Contractor_UserAssociateToType" Member="UserAssociateToTypes" ThisKey="ID" OtherKey="UserID" Type="UserAssociateToType" />
    </Type>
  </Table>
  <Function Name="dbo.UserDeatils_Select" Method="UserDeatils_Select">
    <ElementType Name="UserDeatils_SelectResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UserDetails_Delete" Method="UserDetails_Delete">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UserDetails_Insert" Method="UserDetails_Insert">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Town" Parameter="town" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="County" Parameter="county" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PostCode" Parameter="postCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Country" Parameter="country" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UserDeatils_SelectByID" Method="UserDeatils_SelectByID">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="UserDeatils_SelectByIDResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UserSkills_Select" Method="UserSkills_Select">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="UserSkills_SelectResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Skills" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UserSkills_SelectByUserid" Method="UserSkills_SelectByUserid">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="UserSkills_SelectByUseridResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Skills" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UserSkills_Update" Method="UserSkills_Update">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Skills" Parameter="skills" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SkillLevel" Parameter="skillLevel" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.QuickLinks_Position" Method="QuickLinks_Position">
    <Parameter Name="newPos" Type="System.Int32" DbType="Int" />
    <Parameter Name="oldPos" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID1" Parameter="iD1" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UserDetails_Update" Method="UserDetails_Update">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Town" Parameter="town" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="County" Parameter="county" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PostCode" Parameter="postCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Country" Parameter="country" Type="System.Int32" DbType="Int" />
    <Parameter Name="RangeCovered" Parameter="rangeCovered" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>