<?xml version="1.0" encoding="utf-8"?><Database Name="PlegitDB" Class="ContractorRolesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tblRole" Member="tblRoles">
    <Type Name="tblRole">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>