<?xml version="1.0" encoding="utf-8"?><Database Name="DeffinityEflair" EntityNamespace="Location.Entity" ContextNamespace="Location.DAL" Class="LocationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=69.41.185.220;Initial Catalog=DeffinityEflair;User ID=Deffinity3DBUser;Pooling=True;Min Pool Size=0;Max Pool Size=100;Connect Timeout=60" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBstring" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Country" Member="CountryClasses">
    <Type Name="CountryClass">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country" Member="Country1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="CountryClass_City" Member="Cities" ThisKey="ID" OtherKey="CountryID" Type="City" />
    </Type>
  </Table>
  <Table Name="dbo.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site" Member="Site1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Visible" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="City_Site" Member="City" ThisKey="CityID" OtherKey="ID" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AssignedSitesToPortfolio" Member="AssignedSitesToPortfolios">
    <Type Name="AssignedSitesToPortfolio">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Portfolio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Member="City1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Visible" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="City_Site" Member="Sites" ThisKey="ID" OtherKey="CityID" Type="Site" />
      <Association Name="CountryClass_City" Member="CountryClass" ThisKey="CountryID" OtherKey="ID" Type="CountryClass" IsForeignKey="true" />
    </Type>
  </Table>
</Database>