<?xml version="1.0" encoding="utf-8"?><Database Name="DeffinityEflair" EntityNamespace="MovesAssets.Entity" ContextNamespace="MovesAssets.DAL" Class="MovesAssetsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=69.41.185.219;Initial Catalog=DeffinityEflair;User ID=sa;Pooling=True;Min Pool Size=0;Max Pool Size=100;Connect Timeout=60" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBstring" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AssetMove" Member="AssetMoves">
    <Type Name="AssetMove">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoveRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FromMove" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToMove" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExistingGOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProposedGOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumberofItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Movedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IncidentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="chkstatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_AssetMove" Member="v_AssetMoves">
    <Type Name="v_AssetMove">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoveRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FromMove" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToMove" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExistingGOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProposedGOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberofItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncidentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="chkstatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerEquipment" Member="CustomerEquipments">
    <Type Name="CustomerEquipment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAllocated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoggedbyUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EquipmentName" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeffinityRequestDCEquipment" Member="DeffinityRequestDCEquipments">
    <Type Name="DeffinityRequestDCEquipment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateLogged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoggedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EquipmentName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AssetEquipmentType" Member="AssetEquipmentTypes">
    <Type Name="AssetEquipmentType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EquipmentType" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.v_MoveAssets" Member="v_MoveAssets">
    <Type Name="v_MoveAsset">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoveRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EquipmentName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Assetnumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Make" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MakeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModelName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FromGop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FromPort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToGOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToPort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Incident" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldLink" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NewLink" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Desk" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MoveAssets" Member="MoveAssets">
    <Type Name="MoveAsset">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EquipmentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Assetnumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Make" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Model" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromGop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FromPort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToGOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToPort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MoveRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Incident" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldLink" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NewLink" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Desk" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoveAssets_Document" Member="MoveAssets_Documents">
    <Type Name="MoveAssets_Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Desk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MovesDeskImage" Member="MovesDeskImages">
    <Type Name="MovesDeskImage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Desk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Moves_DeskNotes" Member="Moves_DeskNotes">
    <Type Name="Moves_DeskNote">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Desk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Moves_DeskStatus" Member="Moves_DeskStatus">
    <Type Name="Moves_DeskStatus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Desk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CheckStatus" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Assets_Make" Method="Assets_Make">
    <ElementType Name="Assets_MakeResult">
      <Column Name="MakeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Make" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Assets_Model" Method="Assets_Model">
    <ElementType Name="Assets_ModelResult">
      <Column Name="ModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MoveAssets_Contractors" Method="MoveAssets_Contractors">
    <ElementType Name="MoveAssets_ContractorsResult">
      <Column Name="IncidentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContractorName" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="MoveRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>