<?xml version="1.0" encoding="utf-8"?><Database Name="DeffinityFirstData" EntityNamespace="RFI.Entity" ContextNamespace="RFI.DAL" Class="RFIDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EMS-PC\SQLEXPRESS2014;Initial Catalog=DeffinityFirstData;User ID=sa;Pooling=True;Min Pool Size=0;Max Pool Size=100;Connect Timeout=60" SettingsObjectName="DeffinityManager.Properties.Settings" SettingsPropertyName="DeffinityFirstDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_Vendors" Member="VendorDetails">
    <Type Name="VendorDetails">
      <Column Name="VendorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HQAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VATNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractorName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupOwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeApproveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NormalBuyingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NormalSellingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeBuyingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeSellingRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EmploymentStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpClassification" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondTSApprover" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isFirstlogin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CasualLabourType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ForcePeriodicPwd" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResetPassword" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CalendarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RFI_Vendor" Member="RFI_Vendors">
    <Type Name="RFI_Vendor">
      <Column Name="VendorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HQAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VATNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>