using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using SqlSrv = Microsoft.ApplicationBlocks.Data;

namespace Deffinity.DAL
{
	/// <summary>
	/// Table RFI_Questionnaire
	/// 
	/// Generated by matricrix's C# Layer Builder
	/// 23/06/2009 17:12:16
	/// 
	/// Remark: Use this class to write custom code.
	/// </summary>
	public class RFI_Questionnaire_DAL : RFI_Questionnaire_Base_DAL
	{
		/// <summary>
		/// Constructor
		/// </summary>
		private RFI_Questionnaire_DAL() { }

        /// <summary>
        /// Fill entity list wrt ProjectReference
        /// </summary>
        public static DataTable Fill(int ProjectReference, int SubsectionID,string spName)
        {
            DataSet dsRFI_Questionnaire = SqlSrv.SqlHelper.ExecuteDataset(Connection.ConnectionString, CommandType.StoredProcedure, spName, new System.Data.SqlClient.SqlParameter[] { new System.Data.SqlClient.SqlParameter("@PROJECTREFERENCE", ProjectReference), new System.Data.SqlClient.SqlParameter("@SUBSECTIONID", SubsectionID) });
            return dsRFI_Questionnaire.Tables[0];
        }

	}
}
