using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.ComponentModel;
using System.Data;

namespace Deffinity.BLL
{
	/// <summary>
	/// Table ContractorContacts
	/// 
	/// Generated by matricrix's C# Layer Builder
	/// 15/07/2009 13:11:51
	/// </summary>
	public class ContractorContacts_Base_SVC
	{

		/// <summary>
		/// Insert entity
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Insert, true)]
		public static int Insert(BE.ContractorContacts oContractorContacts)
		{
			return DAL.ContractorContacts_DAL.Insert(oContractorContacts);
		}

		/// <summary>
		/// Search entity
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Select, true)]
		public static BE.ContractorContacts Select(int id)
		{
			return DAL.ContractorContacts_DAL.Select(id);
		}

		/// <summary>
		/// Check if entity exists
		/// </summary>
		public static bool Exists(int id)
		{
			return DAL.ContractorContacts_DAL.Exists(id);
		}
        /// <summary>
        /// Gets the Contractorid fro vendorid
        /// </summary>
        public static int GetContractorId(int vendorid)
        {
            return DAL.ContractorContacts_DAL.GetContractorId(vendorid);
        }
		/// <summary>
		/// Fill entity list
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Fill, true)]
        public static DataTable Fill(int vendorid)
		{
            return DAL.ContractorContacts_DAL.Fill(vendorid);
		}

		/// <summary>
		/// Update entity
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Update, true)]
		public static int Update(BE.ContractorContacts oContractorContacts)
		{
			return DAL.ContractorContacts_DAL.Update(oContractorContacts);
		}

		/// <summary>
		/// Delete entity record
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Delete, true)]
		public static int Delete(int id)
		{
			return DAL.ContractorContacts_DAL.Delete(id);
		}

		/// <summary>
		/// Delete entity ALL records
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Delete, false)]
		public static int DeleteAll()
		{
			return DAL.ContractorContacts_DAL.DeleteAll();
		}

	}
}
