using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.ComponentModel;
using System.Data;

namespace Deffinity.BLL
{
	/// <summary>
	/// Table RFI_TradingHistory
	/// 
	/// Generated by matricrix's C# Layer Builder
	/// 23/06/2009 17:12:32
	/// 
	/// Remark: Use this class to write custom code.
	/// </summary>
	[DataObjectAttribute]
	public class RFI_TradingHistory_SVC : RFI_TradingHistory_Base_SVC
	{
		/// <summary>
		/// Constructor
		/// </summary>
		private RFI_TradingHistory_SVC() { }

        /// <summary>
        /// Fill entity list WRT VENDORID
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Fill, true)]
        public static DataTable Fill(int VENDORID)
        {
            return DAL.RFI_TradingHistory_DAL.Fill(VENDORID);
        }

	}
}
