using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.ComponentModel;
using System.Data;

namespace Deffinity.BLL
{
	/// <summary>
	/// Table RFI_BOM
	/// 
	/// Generated by matricrix's C# Layer Builder
	/// 17/07/2009 15:59:27
	/// 
	/// Remark: Use this class to write custom code.
	/// </summary>
	[DataObjectAttribute]
	public class RFI_BOM_SVC : RFI_BOM_Base_SVC
	{
		/// <summary>
		/// Constructor
		/// </summary>
		private RFI_BOM_SVC() { }
        /// <summary>
        /// Fill entity list
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Fill, true)]
        public static DataTable FillBOMType()
        {
            return DAL.RFI_BOM_DAL.FillBOMType();
        }
        /// <summary>
        /// Fill entity list wrt Project Reference
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Fill, true)]
        public static DataTable Fill(int ProjectReference, int SubsectionID,int WorkSheetID, string spName)
        {
            return DAL.RFI_BOM_DAL.Fill(ProjectReference, SubsectionID,WorkSheetID,spName);
        }
        public static DataTable GetCurrencies()
        {
            return DAL.RFI_BOM_DAL.GetCurrencies();
        }


	}
}
