using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.ComponentModel;
using System.Data;

namespace Deffinity.BLL
{
	/// <summary>
	/// Table RFI_AV2PStatus
	/// 
	/// Generated by matricrix's C# Layer Builder
	/// 23/06/2009 17:11:53
	/// </summary>
	public class RFI_AV2PStatus_Base_SVC
	{

		/// <summary>
		/// Insert entity
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Insert, true)]
		public static int Insert(BE.RFI_AV2PStatus oRFI_AV2PStatus)
		{
			return DAL.RFI_AV2PStatus_DAL.Insert(oRFI_AV2PStatus);
		}

		/// <summary>
		/// Search entity
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Select, true)]
		public static BE.RFI_AV2PStatus Select(int id)
		{
			return DAL.RFI_AV2PStatus_DAL.Select(id);
		}

		/// <summary>
		/// Check if entity exists
		/// </summary>
		public static bool Exists(int id)
		{
			return DAL.RFI_AV2PStatus_DAL.Exists(id);
		}

		/// <summary>
		/// Fill entity list
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Fill, true)]
		public static DataTable Fill()
		{
			return DAL.RFI_AV2PStatus_DAL.Fill();
		}

		/// <summary>
		/// Update entity
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Update, true)]
		public static int Update(BE.RFI_AV2PStatus oRFI_AV2PStatus)
		{
			return DAL.RFI_AV2PStatus_DAL.Update(oRFI_AV2PStatus);
		}

		/// <summary>
		/// Delete entity record
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Delete, true)]
		public static int Delete(int id)
		{
			return DAL.RFI_AV2PStatus_DAL.Delete(id);
		}

		/// <summary>
		/// Delete entity ALL records
		/// </summary>
		[DataObjectMethod(DataObjectMethodType.Delete, false)]
		public static int DeleteAll()
		{
			return DAL.RFI_AV2PStatus_DAL.DeleteAll();
		}

	}
}
