<?xml version="1.0" encoding="utf-8"?><Database Name="PlegitDB" Class="TasksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Tasks" Member="Taskks">
    <Type Name="Taskk">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLeaf" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PercentDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="refid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="completionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="percentComplete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignedResources" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="[index]" Member="index" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="currID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RAG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="QA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RAGRequired" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ProjectStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProjectEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>