<?xml version="1.0" encoding="utf-8"?><Database Name="PlegitDB" Class="ChatsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MuQaddas\MSSQLSERVER01;Initial Catalog=PlegitDB;Persist Security Info=True;User ID=sada;Trust Server Certificate=True" SettingsObjectName="DeffinityManager.Properties.Settings" SettingsPropertyName="PlegitDBConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Chat" Member="Chats">
    <Type Name="Chat">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SenderEmail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReceiverEmail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>